import 'bootstrap-icons/font/bootstrap-icons.css';
import 'bootstrap/dist/css/bootstrap.min.css';
import 'glightbox/dist/css/glightbox.min.css';
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";

const poppins = Poppins({
  weight: ["400", "500", "600", "700"], // Choose the weights you need
  subsets: ["latin"],                  // The required subset
  variable: "--font-poppins",          // Optional: for Tailwind custom variables
});

export const metadata: Metadata = {
  title: "SISTECH CAFE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={poppins.className}
    >
      <NavBar></NavBar>
      <body className="min-h-full flex flex-col">
        {children}
        </body>
    </html>
  );
}
